TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dds_stress_rig.db
DATA += dds_stress_rig.proto

#=======================================
include $(TOP)/configure/RULES
