TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += tensile_stress_rig_internal.db
DB += lvremote_dds_tensile_stress_rig.db

#=======================================
include $(TOP)/configure/RULES
